---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  project:
    title: Project
    output: true
    permalink: "/project/:path/"
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
- jekyll-compass
exclude:
- Gemfile
- Gemfile.lock
google_font:
  - url: "http://fonts.googleapis.com/css?family=Cousine:400,700,400italic,700italic&subset=latin,vietnamese,latin-ext"
  - url: "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700&subset=latin,vietnamese,latin-ext"
